name: FeatherServerAPI
version: '${version}'
author: Feather
website: https://feathermc.com
main: net.digitalingot.feather.serverapi.bukkit.FeatherBukkitPlugin
load: STARTUP
api-version: "1.13"

permissions:
  feather-server-api.notify:
    description: Grants permission to see notifications
    default: op
  feather-server-api.*:
    default: op
    children:
      - feather-server-api.notify
